#!/bin/bash
#for SSH Failed login attempts and the attempter's source IP

LOGFILE="/var/log/auth.log"

if [ ! -f "$LOGFILE" ]; then
	echo "Log file not found:	$LOGFILE"
	exit 1
fi

echo "Top offending IPs (failed ssh logins):"
echo "------------------------------------------"
grep "Failed password" $LOGFILE \
| sed -E 's/.*Failed password for (invalid user )?(\S+) from (\S+) port (\S+).*/\1\2 from \3 port \4/' \
| sort | uniq -c | sort -nr | head -10

